export interface MenuSelections {
  event_code: string;
  is_custom: boolean | null;
  custom_menu_details: string | null;
  starter_type: string | null;
  canape_package: string | null;
  canape_selections: string[] | null;
  plated_starter: string | null;
  main_course_type: string | null;
  dessert_type: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  buffet_meat_selections: string[] | null;
  buffet_vegetable_selections: string[] | null;
  buffet_starch_selections: string[] | null;
  buffet_salad_selection: string | null;
  karoo_meat_selection: string | null;
  karoo_starch_selection: string[] | null;
  karoo_vegetable_selections: string[] | null;
  karoo_salad_selection: string | null;
  plated_main_selection: string | null;
  plated_salad_selection: string | null;
  dessert_canapes: string[] | null;
  individual_cakes: string[] | null;
  traditional_dessert: string | null;
  other_selections: string[] | null;
  other_selections_quantities: Record<string, number> | null;
  starter_price: number | null;
  main_course_price: number | null;
  dessert_price: number | null;
  other_total_price: number | null;
}