
import { Notification } from "@/types/notification";
import { generateMockNotifications, createErrorNotification } from "./mockNotificationData";

/**
 * Attempts various fallback mechanisms to provide notifications when primary method fails
 */
export async function attemptFallbackNotifications(): Promise<Notification[]> {
  try {
    console.log('Using fallback notification mechanism');
    
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 300));
    
    // Return mock notifications with a different set
    const notifications = generateMockNotifications();
    
    // Add a fallback-specific notification
    notifications.push({
      id: 'fallback-specific',
      title: 'Fallback Notification',
      description: 'This notification was generated by the fallback system',
      createdAt: new Date(),
      type: 'system_notice', 
      read: false,
      actionType: 'acknowledge',
      status: 'sent'
    });
    
    return notifications;
  } catch (error) {
    console.error('All fallback methods failed:', error);
    
    // Return a friendly message
    return [{
      id: 'fallback-notification',
      title: 'No Notifications Available',
      description: 'We were unable to load your notifications. Please try again later.',
      createdAt: new Date(),
      type: 'event_created_unified',
      read: false,
      status: 'sent'
    }];
  }
}
