// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hwvchcnruzzjwixxsngp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dmNoY25ydXp6andpeHhzbmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExNjk1MzQsImV4cCI6MjA0Njc0NTUzNH0.zaAz0t8RNkzQqJB7axIBzqlVase-MB6dH9Fpsleu9oY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);