// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vmkvmbnclfgxcgxpymaf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZta3ZtYm5jbGZneGNneHB5bWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExNzI5ODksImV4cCI6MjA0Njc0ODk4OX0.snFZNmyrF8ytZIweG85DAYKe87J_BRjtUEcb5Q9xADQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);